<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alicia Romero Osuna">

<title>Práctica 6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="guio-es (6)_files/libs/clipboard/clipboard.min.js"></script>
<script src="guio-es (6)_files/libs/quarto-html/quarto.js"></script>
<script src="guio-es (6)_files/libs/quarto-html/popper.min.js"></script>
<script src="guio-es (6)_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="guio-es (6)_files/libs/quarto-html/anchor.min.js"></script>
<link href="guio-es (6)_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="guio-es (6)_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="guio-es (6)_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="guio-es (6)_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="guio-es (6)_files/libs/bootstrap/bootstrap-af9f9d18d8d307a2cf9ee553099620e3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 6</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alicia Romero Osuna </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="práctica-6" class="level1">
<h1>PRÁCTICA 6</h1>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos</h2>
<ol type="1">
<li>Aprender a usar la API de <a href="https://www.ebi.ac.uk/interpro/">Interpro</a>.</li>
<li>Recordar que existen las herramientas <code>datasets</code> y <code>dataformat</code> de <a href="https://www.ncbi.nlm.nih.gov/datasets/docs/v2/">NCBI</a>.</li>
</ol>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>Todas las consultas a InterPro <span class="citation" data-cites="Paysan-Lafosse2022">[@Paysan-Lafosse2022]</span> deben empezar con la dirección de la API: <code>https://www.ebi.ac.uk/interpro/api/</code> <span class="citation" data-cites="interproAPI">[@interproAPI]</span>. Por tanto, guardo esta URL básica como cadena de caracteres en la variable <code>API</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>API <span class="ot">&lt;-</span> <span class="st">'https://www.ebi.ac.uk/interpro/api/'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La API devuelve los datos en un formato llamado JSON, basado en texto plano. Necesitamos un paquete que nos ayude a leer los archivos JSON. Por ejemplo, <code>jsonlite</code> <span class="citation" data-cites="jsonlite">[@jsonlite]</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'jsonlite'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="contar-registros" class="level2">
<h2 class="anchored" data-anchor-id="contar-registros">Contar registros</h2>
<p>En InterPro existen seis tipos principales de datos:</p>
<ul>
<li><em>Entry</em>: elementos funcionales predichos sobre las proteínas. Se pueden distinguir los definidos por cada base de datos: InterPro, Pfam, CDD, etc.</li>
<li><em>Protein</em>: las secuencias proteicas procedentes de UniProtKB. Pueden ser <em>reviewed</em> (Swiss-Prot) o <em>unreviewed</em> (TrEMBL).</li>
<li><em>Taxonomy</em>: Organismo y su linaje del que proviene una proteína. La fuente de estos datos es UniProtKB.</li>
<li><em>Structure</em>: Estructuras tridimensionales de las proteínas. Proporcionadas por la base de datos PDB.</li>
<li><em>Set</em>: Conjuntos de registros (<em>entries</em>) relacionados, de acuerdo con las bases de datos Pfam o CDD.</li>
<li><em>Proteome</em>: Conjuntos de proteínas de un mismo organismo. Proporcionados por UniProtKB.</li>
</ul>
<p>Podemos consultar el número de registros de tipo <em>entry</em> en la URL <code>https://www.ebi.ac.uk/interpro/api/entry</code>, cuyo contenido se muestra aquí:</p>
<pre><code>{
    "entries": {
        "member_databases": {
            "pfam": 25501,
            "cathgene3d": 6566,
            "ssf": 2019,
            "panther": 15912,
            "cdd": 19760,
            "profile": 1399,
            "smart": 1322,
            "ncbifam": 32088,
            "prosite": 1311,
            "prints": 2106,
            "hamap": 2391,
            "pirsf": 3292,
            "sfld": 303,
            "antifam": 278
        },
        "integrated": 62376,
        "unintegrated": 52549,
        "interpro": 49900,
        "all": 165723
    }
}</code></pre>
<p>La función <code>fromJSON</code> del paquete <code>jsonlite</code> nos permite guardar este tipo de datos en una lista de listas. En R, podemos acceder a los elementos de una lista con la función <em>doble corchete</em> <code>[[</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>registros <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'entry'</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>registros[[<span class="dv">1</span>]][[<span class="st">'member_databases'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$pfam
[1] 27208

$cathgene3d
[1] 6566

$ssf
[1] 2019

$panther
[1] 15912

$cdd
[1] 19760

$profile
[1] 1399

$smart
[1] 1322

$ncbifam
[1] 33921

$prosite
[1] 1311

$prints
[1] 2106

$hamap
[1] 2391

$pirsf
[1] 3292

$sfld
[1] 303

$antifam
[1] 278</code></pre>
</div>
</div>
<section id="ejercicio-1" class="level3">
<h3 class="anchored" data-anchor-id="ejercicio-1">Ejercicio 1</h3>
<p><em>Construye las URLs necesarias para determinar el número de registros del resto de tipos: protein, structure, set, y proteome. Fíjate en las posibles fuentes de cada tipo de datos, e intenta guardar la información en variables de tu sesión de R.</em></p>
<p>Para cada caso:</p>
<ul>
<li><p>https://www.ebi.ac.uk/interpro/api/protein</p></li>
<li><p>https://www.ebi.ac.uk/interpro/api/structure</p></li>
<li><p>https://www.ebi.ac.uk/interpro/api/set</p></li>
<li><p>https://www.ebi.ac.uk/interpro/api/proteome</p></li>
</ul>
<p>Para proteína:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>proteina <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'protein'</span>)) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>structure <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'structure'</span>)) </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>set <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'set'</span>)) </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>proteome <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'proteome'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="lista-de-datos-de-algún-tipo" class="level2">
<h2 class="anchored" data-anchor-id="lista-de-datos-de-algún-tipo">Lista de datos de algún tipo</h2>
<p>Si además del tipo de datos (<em>entry</em>, <em>protein</em>, <em>taxonomy</em>…), añadimos a la URL la <em>fuente</em> o base de datos de origen que queremos consultar, obtendremos la lista (completa?) de los registros de ese tipo provenientes de <em>esa</em> base de datos. Consulta los ejemplos siguientes:</p>
<ul>
<li>https://www.ebi.ac.uk/interpro/api/entry/interpro</li>
<li>https://www.ebi.ac.uk/interpro/api/entry/pfam</li>
<li>https://www.ebi.ac.uk/interpro/api/protein/reviewed</li>
<li>https://www.ebi.ac.uk/interpro/api/taxonomy/uniprot</li>
</ul>
<p>Pero, para no saturar los servidores, InterPro sólo devuelve los 20 primeros registros de cada consulta, y ofrece una nueva URL (<em>next</em>) para poder ver o descargar los 20 siguientes.</p>
<p>A continuación, usamos la función <code>fromJSON()</code> de <code>jsonlite</code> para descargar los 20 primeros registros de tipo Pfam y exploramos el resultado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>pfam01 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'entry/pfam'</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(pfam01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "list"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(pfam01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pfam01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "count"    "next"     "previous" "results" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pfam01[[<span class="st">'count'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27481</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pfam01[[<span class="st">'next'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "https://www.ebi.ac.uk/interpro/api/entry/pfam/?cursor=cD1QRjAwMDIw"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pfam01[[<span class="st">'previous'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pfam01[[<span class="st">'results'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   metadata.accession
1             PF00001
2             PF00002
3             PF00003
4             PF00004
5             PF00005
6             PF00006
7             PF00007
8             PF00008
9             PF00009
10            PF00010
11            PF00011
12            PF00012
13            PF00013
14            PF00014
15            PF00015
16            PF00016
17            PF00017
18            PF00018
19            PF00019
20            PF00020
                                                     metadata.name
1                      7 transmembrane receptor (rhodopsin family)
2                       7 transmembrane receptor (Secretin family)
3                   7 transmembrane sweet-taste receptor of 3 GCPR
4  ATPase family associated with various cellular activities (AAA)
5                                                  ABC transporter
6        ATP synthase alpha/beta family, nucleotide-binding domain
7                                              Cystine-knot domain
8                                                  EGF-like domain
9                          Elongation factor Tu GTP binding domain
10                             Helix-loop-helix DNA-binding domain
11                                   Hsp20/alpha crystallin family
12                                                   Hsp70 protein
13                                                       KH domain
14               Kunitz/Bovine pancreatic trypsin inhibitor domain
15     Methyl-accepting chemotaxis protein (MCP) signalling domain
16 Ribulose bisphosphate carboxylase large chain, catalytic domain
17                                                      SH2 domain
18                                                      SH3 domain
19                     Transforming growth factor beta like domain
20                                  TNFR/NGFR cysteine-rich region
   metadata.source_database metadata.type metadata.integrated
1                      pfam        domain           IPR000276
2                      pfam        domain           IPR000832
3                      pfam        domain           IPR017978
4                      pfam        domain           IPR003959
5                      pfam        domain           IPR003439
6                      pfam        domain           IPR000194
7                      pfam        domain           IPR006208
8                      pfam        domain           IPR000742
9                      pfam        domain           IPR000795
10                     pfam        domain           IPR011598
11                     pfam        domain           IPR002068
12                     pfam        family           IPR013126
13                     pfam        domain           IPR004088
14                     pfam        domain           IPR002223
15                     pfam        family           IPR004089
16                     pfam        domain           IPR000685
17                     pfam        domain           IPR000980
18                     pfam        domain           IPR001452
19                     pfam        domain           IPR001839
20                     pfam        domain           IPR001368
   metadata.member_databases metadata.go_terms
1                         NA                NA
2                         NA                NA
3                         NA                NA
4                         NA                NA
5                         NA                NA
6                         NA                NA
7                         NA                NA
8                         NA                NA
9                         NA                NA
10                        NA                NA
11                        NA                NA
12                        NA                NA
13                        NA                NA
14                        NA                NA
15                        NA                NA
16                        NA                NA
17                        NA                NA
18                        NA                NA
19                        NA                NA
20                        NA                NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pfam01[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   accession                                                            name
1    PF00001                     7 transmembrane receptor (rhodopsin family)
2    PF00002                      7 transmembrane receptor (Secretin family)
3    PF00003                  7 transmembrane sweet-taste receptor of 3 GCPR
4    PF00004 ATPase family associated with various cellular activities (AAA)
5    PF00005                                                 ABC transporter
6    PF00006       ATP synthase alpha/beta family, nucleotide-binding domain
7    PF00007                                             Cystine-knot domain
8    PF00008                                                 EGF-like domain
9    PF00009                         Elongation factor Tu GTP binding domain
10   PF00010                             Helix-loop-helix DNA-binding domain
11   PF00011                                   Hsp20/alpha crystallin family
12   PF00012                                                   Hsp70 protein
13   PF00013                                                       KH domain
14   PF00014               Kunitz/Bovine pancreatic trypsin inhibitor domain
15   PF00015     Methyl-accepting chemotaxis protein (MCP) signalling domain
16   PF00016 Ribulose bisphosphate carboxylase large chain, catalytic domain
17   PF00017                                                      SH2 domain
18   PF00018                                                      SH3 domain
19   PF00019                     Transforming growth factor beta like domain
20   PF00020                                  TNFR/NGFR cysteine-rich region
   source_database   type integrated member_databases go_terms
1             pfam domain  IPR000276               NA       NA
2             pfam domain  IPR000832               NA       NA
3             pfam domain  IPR017978               NA       NA
4             pfam domain  IPR003959               NA       NA
5             pfam domain  IPR003439               NA       NA
6             pfam domain  IPR000194               NA       NA
7             pfam domain  IPR006208               NA       NA
8             pfam domain  IPR000742               NA       NA
9             pfam domain  IPR000795               NA       NA
10            pfam domain  IPR011598               NA       NA
11            pfam domain  IPR002068               NA       NA
12            pfam family  IPR013126               NA       NA
13            pfam domain  IPR004088               NA       NA
14            pfam domain  IPR002223               NA       NA
15            pfam family  IPR004089               NA       NA
16            pfam domain  IPR000685               NA       NA
17            pfam domain  IPR000980               NA       NA
18            pfam domain  IPR001452               NA       NA
19            pfam domain  IPR001839               NA       NA
20            pfam domain  IPR001368               NA       NA</code></pre>
</div>
</div>
<p>Los siguientes 20 registros de Pfam se encuentran en <code>pfam01[['next']]</code>: https://www.ebi.ac.uk/interpro/api/entry/pfam/?cursor=cD1QRjAwMDIw. Y los podemos descargar igual.</p>
<p><strong>Nota:</strong> No me deja instalarme el paquete “kableExtra”, asi que sustituyo por “knitr”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'knitr'</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>pfam02 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(pfam01[[<span class="st">'next'</span>]])</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pfam02[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 31%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">accession</th>
<th style="text-align: left;">name</th>
<th style="text-align: left;">source_database</th>
<th style="text-align: left;">type</th>
<th style="text-align: left;">integrated</th>
<th style="text-align: left;">member_databases</th>
<th style="text-align: left;">go_terms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PF00021</td>
<td style="text-align: left;">u-PAR/Ly-6 domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR016054</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00022</td>
<td style="text-align: left;">Actin</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">family</td>
<td style="text-align: left;">IPR004000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00023</td>
<td style="text-align: left;">Ankyrin repeat</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">repeat</td>
<td style="text-align: left;">IPR002110</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00024</td>
<td style="text-align: left;">PAN domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR003609</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00025</td>
<td style="text-align: left;">ADP-ribosylation factor family</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR006689</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00026</td>
<td style="text-align: left;">Eukaryotic aspartyl protease</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR033121</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00027</td>
<td style="text-align: left;">Cyclic nucleotide-binding domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000595</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00028</td>
<td style="text-align: left;">Cadherin domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR002126</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00029</td>
<td style="text-align: left;">Connexin</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR013092</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00030</td>
<td style="text-align: left;">Beta/Gamma crystallin</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001064</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00031</td>
<td style="text-align: left;">Cystatin domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000010</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00032</td>
<td style="text-align: left;">Cytochrome b(C-terminal)/b6/petD</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR005798</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00033</td>
<td style="text-align: left;">Cytochrome b/b6/petB</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR005797</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00034</td>
<td style="text-align: left;">Cytochrome c</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR009056</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00035</td>
<td style="text-align: left;">Double-stranded RNA binding motif</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR014720</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00036</td>
<td style="text-align: left;">EF hand domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR002048</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00037</td>
<td style="text-align: left;">4Fe-4S binding domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR017896</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00038</td>
<td style="text-align: left;">Intermediate filament protein</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">coiled_coil</td>
<td style="text-align: left;">IPR039008</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00039</td>
<td style="text-align: left;">Fibronectin type I domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000083</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00040</td>
<td style="text-align: left;">Fibronectin type II domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000562</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="ejercicio-2" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-2">Ejercicio 2</h2>
<p><em>Crea una tercera lista con los contenidos de la tercera página de registros de Pfam.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'knitr'</span>) </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'jsonlite'</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>pfam03 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(pfam02[[<span class="st">'next'</span>]]) </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pfam03[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 46%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">accession</th>
<th style="text-align: left;">name</th>
<th style="text-align: left;">source_database</th>
<th style="text-align: left;">type</th>
<th style="text-align: left;">integrated</th>
<th style="text-align: left;">member_databases</th>
<th style="text-align: left;">go_terms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PF00041</td>
<td style="text-align: left;">Fibronectin type III domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR003961</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00042</td>
<td style="text-align: left;">Globin</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000971</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00043</td>
<td style="text-align: left;">Glutathione S-transferase, C-terminal domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR004046</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00044</td>
<td style="text-align: left;">Glyceraldehyde 3-phosphate dehydrogenase, NAD binding domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR020828</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00045</td>
<td style="text-align: left;">Hemopexin</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">repeat</td>
<td style="text-align: left;">IPR018487</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00046</td>
<td style="text-align: left;">Homeodomain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001356</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00047</td>
<td style="text-align: left;">Immunoglobulin domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR013151</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00048</td>
<td style="text-align: left;">Small cytokines (intecrine/chemokine), interleukin-8 like</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001811</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00049</td>
<td style="text-align: left;">Insulin/IGF/Relaxin family</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR016179</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00050</td>
<td style="text-align: left;">Kazal-type serine protease inhibitor domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR002350</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00051</td>
<td style="text-align: left;">Kringle domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000001</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00052</td>
<td style="text-align: left;">Laminin B (Domain IV)</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR000034</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00053</td>
<td style="text-align: left;">Laminin EGF domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR002049</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00054</td>
<td style="text-align: left;">Laminin G domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001791</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00055</td>
<td style="text-align: left;">Laminin N-terminal (Domain VI)</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR008211</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00056</td>
<td style="text-align: left;">lactate/malate dehydrogenase, NAD binding domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001236</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00057</td>
<td style="text-align: left;">Low-density lipoprotein receptor domain class A</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">repeat</td>
<td style="text-align: left;">IPR002172</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00058</td>
<td style="text-align: left;">Low-density lipoprotein receptor repeat class B</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">repeat</td>
<td style="text-align: left;">IPR000033</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF00059</td>
<td style="text-align: left;">Lectin C-type domain</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">domain</td>
<td style="text-align: left;">IPR001304</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PF00060</td>
<td style="text-align: left;">Ligand-gated ion channel</td>
<td style="text-align: left;">pfam</td>
<td style="text-align: left;">family</td>
<td style="text-align: left;">IPR001320</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="unión-de-páginas-en-un-mismo-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="unión-de-páginas-en-un-mismo-data-frame">Unión de <em>páginas</em> en un mismo <em>data frame</em></h2>
<p>El paquete <code>jsonlite</code> nos ofrece la función <code>rbind_pages()</code> para juntar una lista de <em>data frames</em> en uno solo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pfam <span class="ot">&lt;-</span> <span class="fu">rbind_pages</span>(<span class="fu">list</span>(pfam01[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]],</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                         pfam02[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Pero para leer y descargar todas las páginas, necesitaríamos alguna manera de automatizar el proceso. En el Apéndice 2 encontrarás una solución posible.</p>
</section>
<section id="mostrar-todos-los-detalles-de-un-registro-concreto" class="level2">
<h2 class="anchored" data-anchor-id="mostrar-todos-los-detalles-de-un-registro-concreto">Mostrar todos los detalles de un registro concreto</h2>
<p>Ya sabemos cómo mostrar el número de registros de un tipo y cómo descargar la lista de todos ellos (de 20 en 20). El siguiente paso es descargar toda la información relativa a un registro concreto, del cual debemos saber su identificador. Por ejemplo, el dominio PF06235 de Pfam. Para ello, añadimos un tercer campo a la URL, después del tipo de datos y del nombre de la base de datos de procedencia: el identificador del registro que queremos descargar:</p>
<p>https://www.ebi.ac.uk/interpro/api/entry/pfam/PF06235</p>
<p>La función genérica <code>str()</code> de R nos describe la estructura de cualquier objeto en R, y nos puede ayudar a entender cómo podemos acceder a cada dato del registro:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>pf06235 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'entry/pfam/PF06235'</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pf06235)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 1
 $ metadata:List of 21
  ..$ accession               : chr "PF06235"
  ..$ entry_id                : NULL
  ..$ type                    : chr "family"
  ..$ go_terms                : NULL
  ..$ source_database         : chr "pfam"
  ..$ member_databases        : NULL
  ..$ integrated              : chr "IPR009356"
  ..$ hierarchy               : NULL
  ..$ name                    :List of 2
  .. ..$ name : chr "NADH dehydrogenase subunit 4L (NAD4L)"
  .. ..$ short: chr "NAD4L"
  ..$ description             :'data.frame':    1 obs. of  4 variables:
  .. ..$ text   : chr "&lt;p&gt;This family consists of NADH dehydrogenase subunit 4L (NAD4L) proteins from the mitochondria of several para"| __truncated__
  .. ..$ llm    : logi FALSE
  .. ..$ checked: logi FALSE
  .. ..$ updated: logi FALSE
  ..$ wikipedia               : NULL
  ..$ literature              : NULL
  ..$ set_info                : NULL
  ..$ overlaps_with           : NULL
  ..$ counters                :List of 11
  .. ..$ subfamilies         : int 0
  .. ..$ domain_architectures: int 3
  .. ..$ interactions        : int 0
  .. ..$ matches             : int 402
  .. ..$ pathways            : int 0
  .. ..$ proteins            : int 402
  .. ..$ proteomes           : int 8
  .. ..$ sets                : int 0
  .. ..$ structural_models   :List of 2
  .. .. ..$ alphafold: int 401
  .. .. ..$ bfvd     : int 0
  .. ..$ structures          : int 0
  .. ..$ taxa                : int 645
  ..$ entry_annotations       :List of 4
  .. ..$ hmm           : int 0
  .. ..$ logo          : int 0
  .. ..$ alignment:seed: int 12
  .. ..$ alignment:full: int 9
  ..$ cross_references        : Named list()
  ..$ is_llm                  : logi FALSE
  ..$ is_reviewed_llm         : logi FALSE
  ..$ is_updated_llm          : logi FALSE
  ..$ representative_structure: NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>nombre_largo <span class="ot">&lt;-</span> pf06235[[<span class="st">'metadata'</span>]][[<span class="st">'name'</span>]][[<span class="st">'name'</span>]]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>nombre_largo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "NADH dehydrogenase subunit 4L (NAD4L)"</code></pre>
</div>
</div>
<p>Obtenemos lo siguiente al ejecutar este bloque: “<u>NADH dehydrogenase subunit 4L (NAD4L)</u>”</p>
<section id="ejercicio-3" class="level3">
<h3 class="anchored" data-anchor-id="ejercicio-3">Ejercicio 3</h3>
<p><em>Usa la función <code>fromJSON()</code> para guardar la información del registro P01923 (proteína de Swiss-Prot) y explora la estructura de los datos con la función <code>str()</code>. ¿Puedes extraer la secuencia?</em></p>
<p>Siguiendo la misma estructura del comando anterior, lo hago para P01923:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>p01923 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'protein/reviewed/P01923'</span>)) </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(p01923) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 1
 $ metadata:List of 17
  ..$ accession       : chr "P01923"
  ..$ id              : chr "HBA_GORGO"
  ..$ source_organism :List of 3
  .. ..$ taxId         : chr "9595"
  .. ..$ scientificName: chr "Gorilla gorilla gorilla"
  .. ..$ fullName      : chr "Gorilla gorilla gorilla (Western lowland gorilla)"
  ..$ name            : chr "Hemoglobin subunit alpha"
  ..$ description     : chr [1:2] "Involved in oxygen transport from the lung to the various peripheral tissues" "Hemopressin acts as an antagonist peptide of the cannabinoid receptor CNR1. Hemopressin-binding efficiently blo"| __truncated__
  ..$ length          : int 141
  ..$ sequence        : chr "VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAA"| __truncated__
  ..$ proteome        : chr "UP000001519"
  ..$ gene            : chr "HBA"
  ..$ go_terms        :'data.frame':    5 obs. of  3 variables:
  .. ..$ identifier: chr [1:5] "GO:0019825" "GO:0020037" "GO:0015671" "GO:0005833" ...
  .. ..$ name      : chr [1:5] "oxygen binding" "heme binding" "oxygen transport" "hemoglobin complex" ...
  .. ..$ category  :'data.frame':   5 obs. of  2 variables:
  .. .. ..$ code: chr [1:5] "F" "F" "P" "C" ...
  .. .. ..$ name: chr [1:5] "molecular_function" "molecular_function" "biological_process" "cellular_component" ...
  ..$ protein_evidence: int 1
  ..$ source_database : chr "reviewed"
  ..$ is_fragment     : logi FALSE
  ..$ in_alphafold    : logi TRUE
  ..$ in_bfvd         : logi FALSE
  ..$ ida_accession   : chr "479f10f36c30dd70c041c861502b6b89292a259d"
  ..$ counters        :List of 11
  .. ..$ domain_architectures: int 26315
  .. ..$ entries             : int 14
  .. ..$ isoforms            : int 0
  .. ..$ proteomes           : int 1
  .. ..$ sets                : int 2
  .. ..$ structures          : int 0
  .. ..$ taxa                : int 1
  .. ..$ dbEntries           :List of 8
  .. .. ..$ cathgene3d: int 1
  .. .. ..$ profile   : int 1
  .. .. ..$ ssf       : int 1
  .. .. ..$ cdd       : int 1
  .. .. ..$ pfam      : int 1
  .. .. ..$ panther   : int 1
  .. .. ..$ prints    : int 2
  .. .. ..$ interpro  : int 6
  .. ..$ proteome            : int 1
  .. ..$ taxonomy            : int 1
  .. ..$ similar_proteins    : int 26315</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>secuencia <span class="ot">&lt;-</span> p01923[[<span class="st">'metadata'</span>]][[<span class="st">'sequence'</span>]] </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>secuencia</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR"</code></pre>
</div>
</div>
<p>La secuencia extraída es la siguiente:“VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR”</p>
</section>
</section>
<section id="filtros.-cruzar-dos-tipos-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="filtros.-cruzar-dos-tipos-de-datos">Filtros. Cruzar dos tipos de datos</h2>
<p>Hasta ahora hemos construido una URL con hasta tres elementos: el tipo de datos, la base de datos de procedencia, y el identificador concreto. Estos tres elementos constituyen el <em>bloque de punto final</em> de la URL. También hemos visto que InterPro devuelve una estructura de datos diferente en función de cuantos de esos tres elementos usamos (sólo el tipo de datos es obligatorio): un recuento de registros, una lista de registros, o toda la información de un registro concreto.</p>
<p>Si al <em>bloque de punto final</em> añadimos un segundo tipo de datos, obtendremos un recuento o una lista del primer tipo de datos con información sobre el segundo. Por ejemplo, al comparar estas 2 URLs:</p>
<ul>
<li>https://www.ebi.ac.uk/interpro/api/protein</li>
<li>https://www.ebi.ac.uk/interpro/api/protein/entry</li>
</ul>
<p>podemos observar que no en todas las proteínas en UniProtKB se encuentra algún dominio o elemento funcional en InterPro.</p>
<section id="ejercicio-4" class="level3">
<h3 class="anchored" data-anchor-id="ejercicio-4">Ejercicio 4</h3>
<p><em>Determina cuántos taxones de UniProtKB no tienen ninguna proteína asignada. ¿Y qué proporción de proteínas cuentan con una estructura terciaria?</em></p>
<p>Ahora usamos la taxonomía, cuyos datos provienen de UniProtKB.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>taxonomy <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API,<span class="st">'taxonomy'</span>)) </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>taxonomyprotein <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'taxonomy/protein'</span>)) </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(taxonomy) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 1
 $ taxa:List of 1
  ..$ uniprot: int 2678841</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(taxonomyprotein)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ taxa    :List of 1
  ..$ uniprot: int 1291419
 $ proteins:List of 3
  ..$ unreviewed: int 201794580
  ..$ reviewed  : int 571702
  ..$ uniprot   : int 202150435</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>taxones_total <span class="ot">&lt;-</span> taxonomy[[<span class="st">'taxa'</span>]][[<span class="st">'uniprot'</span>]]<span class="sc">-</span>taxonomyprotein[[<span class="st">'taxa'</span>]][[<span class="st">'uniprot'</span>]] </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>taxones_total </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1387422</code></pre>
</div>
</div>
<p>Por tanto, el número total de taxones que no tienen proteína asignada es de 1387422.</p>
<p>Ahora siguiendo los mismos pasos lo hacemos pero para la estructura terciaria, usando “structure” en vez de “taxonomy”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>protein <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API,<span class="st">'protein'</span>)) </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>proteinstructure <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'protein/structure'</span>)) </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(protein) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 1
 $ proteins:List of 3
  ..$ unreviewed: int 201794580
  ..$ reviewed  : int 571702
  ..$ uniprot   : int 202150435</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(proteinstructure) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ proteins  :List of 3
  ..$ reviewed  : int 37334
  ..$ unreviewed: int 30128
  ..$ uniprot   : int 67874
 $ structures:List of 1
  ..$ pdb: int 228088</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>prot3d <span class="ot">&lt;-</span> protein[[<span class="st">'proteins'</span>]][[<span class="st">'uniprot'</span>]]</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>proteinstructure[[<span class="st">'proteins'</span>]][[<span class="st">'uniprot'</span>]] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67874</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>prot3d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 202150435</code></pre>
</div>
</div>
<p>El número total de estructuras primarias es de 202082561. Mientras que 67874 es el número total de estructuras tridimensionales.</p>
<p><strong>Nota:</strong> he usado proteins = tanto reviewed como unreviewed.</p>
</section>
</section>
<section id="filtros.-subconjunto-de-registros" class="level2">
<h2 class="anchored" data-anchor-id="filtros.-subconjunto-de-registros">Filtros. Subconjunto de registros</h2>
<p>Podemos especificar un registro concreto de un tipo de datos para limitar una lista de registros de otro tipo de datos. Por ejemplo, la lista de proteínas de la base de datos <em>reviewed</em> (Swiss-Prot) anotadas con la familia Pfam PF00019 (<em>Transforming grow factor beta like domain</em>):</p>
<p>https://www.ebi.ac.uk/interpro/api/protein/reviewed/entry/pfam/PF00019</p>
<p>Para extraer la información desde R, tenemos que familiarizarnos con la estructura de los datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>pfam00019 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'protein/reviewed/entry/pfam/PF00019'</span>))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pfam00019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "count"    "next"     "previous" "results" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>pfam00019[[<span class="st">'count'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 229</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pfam00019[[<span class="st">'results'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "metadata" "entries" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La función "flaten()" corrige el anidamiento de marcos de datos,</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">flatten</span>(pfam00019[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">accession</th>
<th style="text-align: left;">name</th>
<th style="text-align: left;">source_database</th>
<th style="text-align: right;">length</th>
<th style="text-align: left;">gene</th>
<th style="text-align: left;">in_alphafold</th>
<th style="text-align: left;">in_bfvd</th>
<th style="text-align: left;">source_organism.taxId</th>
<th style="text-align: left;">source_organism.scientificName</th>
<th style="text-align: left;">source_organism.fullName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A1C2U3</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9600</td>
<td style="text-align: left;">Pongo pygmaeus</td>
<td style="text-align: left;">Pongo pygmaeus (Bornean orangutan)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A1C2U6</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9544</td>
<td style="text-align: left;">Macaca mulatta</td>
<td style="text-align: left;">Macaca mulatta (Rhesus macaque)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A1C2U7</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9597</td>
<td style="text-align: left;">Pan paniscus</td>
<td style="text-align: left;">Pan paniscus (Pygmy chimpanzee)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A1C2V0</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9598</td>
<td style="text-align: left;">Pan troglodytes</td>
<td style="text-align: left;">Pan troglodytes (Chimpanzee)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A1C2V5</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9595</td>
<td style="text-align: left;">Gorilla gorilla gorilla</td>
<td style="text-align: left;">Gorilla gorilla gorilla (Western lowland gorilla)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A8E7N9</td>
<td style="text-align: left;">Growth/differentiation factor 6-B</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">412</td>
<td style="text-align: left;">gdf6b</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">7955</td>
<td style="text-align: left;">Danio rerio</td>
<td style="text-align: left;">Danio rerio (Zebrafish)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A9CB18</td>
<td style="text-align: left;">Growth/differentiation factor 9</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">455</td>
<td style="text-align: left;">GDF9</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9555</td>
<td style="text-align: left;">Papio anubis</td>
<td style="text-align: left;">Papio anubis (Olive baboon)</td>
</tr>
<tr class="even">
<td style="text-align: left;">F1QWZ4</td>
<td style="text-align: left;">Growth/differentiation factor 2</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">389</td>
<td style="text-align: left;">gdf2</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">7955</td>
<td style="text-align: left;">Danio rerio</td>
<td style="text-align: left;">Danio rerio (Zebrafish)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G5EBY8</td>
<td style="text-align: left;">BMP-like protein unc-129</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">407</td>
<td style="text-align: left;">unc-129</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">6239</td>
<td style="text-align: left;">Caenorhabditis elegans</td>
<td style="text-align: left;">Caenorhabditis elegans</td>
</tr>
<tr class="even">
<td style="text-align: left;">G5EEL5</td>
<td style="text-align: left;">Protein dbl-1</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">365</td>
<td style="text-align: left;">dbl-1</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">6239</td>
<td style="text-align: left;">Caenorhabditis elegans</td>
<td style="text-align: left;">Caenorhabditis elegans</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G7PWZ3</td>
<td style="text-align: left;">Growth/differentiation factor 15</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">308</td>
<td style="text-align: left;">GDF15</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9541</td>
<td style="text-align: left;">Macaca fascicularis</td>
<td style="text-align: left;">Macaca fascicularis (Crab-eating macaque)</td>
</tr>
<tr class="even">
<td style="text-align: left;">O00292</td>
<td style="text-align: left;">Left-right determination factor 2</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">366</td>
<td style="text-align: left;">LEFTY2</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9606</td>
<td style="text-align: left;">Homo sapiens</td>
<td style="text-align: left;">Homo sapiens (Human)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O08689</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">376</td>
<td style="text-align: left;">Mstn</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">10090</td>
<td style="text-align: left;">Mus musculus</td>
<td style="text-align: left;">Mus musculus (Mouse)</td>
</tr>
<tr class="even">
<td style="text-align: left;">O08717</td>
<td style="text-align: left;">Inhibin beta E chain</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">350</td>
<td style="text-align: left;">Inhbe</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">10090</td>
<td style="text-align: left;">Mus musculus</td>
<td style="text-align: left;">Mus musculus (Mouse)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O13048</td>
<td style="text-align: left;">Nodal homolog 4-A</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">402</td>
<td style="text-align: left;">nodal4-a</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">8355</td>
<td style="text-align: left;">Xenopus laevis</td>
<td style="text-align: left;">Xenopus laevis (African clawed frog)</td>
</tr>
<tr class="even">
<td style="text-align: left;">O14793</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9606</td>
<td style="text-align: left;">Homo sapiens</td>
<td style="text-align: left;">Homo sapiens (Human)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O18828</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9557</td>
<td style="text-align: left;">Papio hamadryas</td>
<td style="text-align: left;">Papio hamadryas (Hamadryas baboon)</td>
</tr>
<tr class="even">
<td style="text-align: left;">O18830</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9940</td>
<td style="text-align: left;">Ovis aries</td>
<td style="text-align: left;">Ovis aries (Sheep)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O18831</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9823</td>
<td style="text-align: left;">Sus scrofa</td>
<td style="text-align: left;">Sus scrofa (Pig)</td>
</tr>
<tr class="even">
<td style="text-align: left;">O18836</td>
<td style="text-align: left;">Growth/differentiation factor 8</td>
<td style="text-align: left;">reviewed</td>
<td style="text-align: right;">375</td>
<td style="text-align: left;">MSTN</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">9913</td>
<td style="text-align: left;">Bos taurus</td>
<td style="text-align: left;">Bos taurus (Bovine)</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="ejercicio-5" class="level3">
<h3 class="anchored" data-anchor-id="ejercicio-5">Ejercicio 5</h3>
<p><em>Intenta obtener una lista de los dominios de Pfam presentes en vertebrados (taxon 7742). Al menos, los 20 primeros.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>vertebrados <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'entry/pfam/taxonomy/uniprot/7742'</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(vertebrados)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>vertebrados[[<span class="st">'results'</span>]][[<span class="st">'metadata'</span>]]</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(vertebrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Se ha usado <code>#| eval: false</code> ,<code>#| message: false</code>y <code>#| warning: false</code> para facilitar la visualización al renderizarlo.</p>
</blockquote>
</section>
<section id="ejercicio-6" class="level3">
<h3 class="anchored" data-anchor-id="ejercicio-6">Ejercicio 6</h3>
<p><em>¿Cuántas proteínas de cocodrilos (taxon 8493) conocemos con el dominio zinc finger, C2HC type (Pfam PF01530)?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pfam01530 <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">paste0</span>(API, <span class="st">'protein/uniprot/entry/pfam/PF01530/taxonomy/uniprot/8493'</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pfam01530)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "count"    "next"     "previous" "results" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>pfam01530[[<span class="st">'count'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
</div>
<p>Se conocen 15 proteínas de cocodrilos con el dominio <em>zinc finger, C2HC type</em> (Pfam PF01530).</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>